config/routes.rb
Rails.application.routes.draw do
  resources :sources, except: :show
  
  resources :users
  get '/registration', to: 'users#registration', as: 'registration'
  post '/register', to: 'users#register', as: 'register'
  resources :password_resets, only: %i[new create edit update]
  resource :user_session  
  
  resources :users_groups do
    resources :users_group_members, only: %i[create destroy]
    resources :organization_restrictions, only: %i[create destroy]
    resources :division_restrictions, only: %i[create destroy]
  end

  resources :expenses, only: %i[index show] do
    collection do
      get '/page/:page', action: :index
      get 'list'
    end
  end
  put '/expenses/:id/agree', to: 'expenses#agree', as: 'expense_agree'
  put '/expenses/:id/disagree', to: 'expenses#disagree', as: 'expense_disagree'

  resources :external_apps, except: :show

  get '/permission_error', to: 'pages#permission_error', as: 'permission_error'
  root "pages#home"

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'expenses', to: 'expenses#create'
        patch 'expense', to: 'expenses#update'
        put 'expense', to: 'expenses#update'
        delete 'expense', to: 'expenses#destroy'

        post 'organizations', to: 'organizations#create'
        patch 'organization', to: 'organizations#update'
        put 'organization', to: 'organizations#update'
        delete 'organization', to: 'organizations#destroy'

        post 'divisions', to: 'divisions#create'
        patch 'division', to: 'divisions#update'
        put 'division', to: 'divisions#update'
        delete 'division', to: 'divisions#destroy'
      end
    end
  end
end

app/models/source.rb
class Source < ApplicationRecord
  include Externable

  has_many :expenses, dependent: :restrict_with_error

  validates :name, presence: true
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :require_login
  before_action :require_admin
  before_action :set_source, only: %i[edit update destroy]

  def index
    @sources = Source.all
  end

  def new
    @source = Source.new
  end

  def create
    @source = Source.new(source_params)

    if @source.save
      redirect_to sources_path, notice: 'Источник денежных средств создан успешно.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @source.update(source_params)
      redirect_to sources_path, notice: 'Источник денежных средств изменен успешно.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @source.destroy
    if @source.destroyed?
      redirect_to sources_path, notice: 'Источник денежных средств удален.'
    else
      redirect_to sources_path, notice: @source.errors.full_messages.to_sentence.capitalize
    end
  end

  private

  def source_params
    params.require(:source).permit(:name, :externalid)
  end

  def set_source
    @source = Source.find(params[:id])
  end
end

app/views/sources/_form.html.erb
<%= form_with model: source do |form| %>
  <%= render 'layouts/form_errors', object: source %>

  <div>
    <%= form.label :name, "Наименование:" %>
    <%= form.text_field :name %>
  </div>
  <div>  
    <%= form.label :name, "Внешний ID:" %>
    <%= form.text_field :externalid %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sources/_source.html.erb
<div>
  <div>
    <%= source.name %>
  </div>
  <div>
    <%= source.externalid %>
  </div>
  <div>
    <%= link_to "Изменить", edit_source_path(source) %>
    <%= button_to "Удалить", source_path(source), method: :delete %>
  </div>
</div>
<hr>

app/views/sources/edit.html.erb
<h1>Банковский счет/Касса</h1>
<%= render "form", source: @source %>

app/views/sources/index.html.erb
<h1>Банковский счет/Касса</h1>
<%= link_to "Добавить", new_source_path %>
<br>
<br>
<%= render @sources %>

app/views/sources/new.html.erb
<h1>Новый банковский счет/касса</h1>
<%= render "form", source: @source %>