config/routes.rb
Rails.application.routes.draw do
  resources :sources, except: :show
  
  resources :users
  get '/registration', to: 'users#registration', as: 'registration'
  post '/register', to: 'users#register', as: 'register'
  resources :password_resets, only: %i[new create edit update]
  resource :user_session  
  
  resources :users_groups do
    resources :users_group_members, only: %i[create destroy]
    resources :organization_restrictions, only: %i[create destroy]
    resources :division_restrictions, only: %i[create destroy]
  end

  resources :expenses, only: %i[index show] do
    collection do
      get '/page/:page', action: :index
      get 'list'
    end
  end
  put '/expenses/:id/agree', to: 'expenses#agree', as: 'expense_agree'
  put '/expenses/:id/disagree', to: 'expenses#disagree', as: 'expense_disagree'

  resources :external_apps, except: :show

  get '/permission_error', to: 'pages#permission_error', as: 'permission_error'
  root "pages#home"

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'expenses', to: 'expenses#create'
        patch 'expense', to: 'expenses#update'
        put 'expense', to: 'expenses#update'
        delete 'expense', to: 'expenses#destroy'

        post 'organizations', to: 'organizations#create'
        patch 'organization', to: 'organizations#update'
        put 'organization', to: 'organizations#update'
        delete 'organization', to: 'organizations#destroy'

        post 'divisions', to: 'divisions#create'
        patch 'division', to: 'divisions#update'
        put 'division', to: 'divisions#update'
        delete 'division', to: 'divisions#destroy'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users_group_members, dependent: :destroy
  has_many :users_groups, through: :users_group_members
  has_many :division_restrictions, through: :users_groups
  has_many :divisions, through: :division_restrictions
  has_many :organization_restrictions, through: :users_groups
  has_many :organizations, through: :organization_restrictions

  has_many :expense_responsible, class_name: 'Expense', foreign_key: 'responsible_id', dependent: :restrict_with_error

  acts_as_authentic do |c|
    c.crypto_provider = ::Authlogic::CryptoProviders::SCrypt
  end

  validates :email,
            format: {
              with: /@/,
              message: 'should look like an email address.'
            },
            length: { maximum: 100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_email?
            },
            presence: true

  validates :login,
            format: {
              with: /\A[a-z0-9]+\z/,
              message: 'should use only letters and numbers.'
            },
            length: { within: 3..100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_login?
            }

  validates :password, confirmation: { if: :require_password? }

  validate :must_exist_admin_on_update, on: :update
  before_destroy :must_exist_admin_on_destroy

  scope :admins, -> { where(is_admin: true) }

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def restricted_objects
    restricted_divisions = divisions
    related_organizations_ids = restricted_divisions.pluck(:organization_id)
    restricted_organizations = organizations.where.not(id: related_organizations_ids)
    [restricted_organizations, restricted_divisions]
  end

  private

  def must_exist_admin_on_update
    return unless is_admin_was && is_admin_changed? && User.admins.count == 1

    errors.add(:base, 'В приложении не останется ни одного администратора!')
  end

  def must_exist_admin_on_destroy
    return unless is_admin && User.admins.count == 1

    errors.add(:base, 'В приложении не останется ни одного администратора!')
    throw :abort
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_registration, only: %i[registration register]
  before_action :require_login, except: %i[registration register]
  before_action :require_admin, except: %i[registration register]
  before_action :set_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to users_path, notice: 'Пользователь создан.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def registration
    @user = User.new
  end

  def register
    @user = User.new(users_params)
    @user.is_admin = true
    if @user.save
      redirect_to root_path, notice: 'Регистрация выполнена.'
    else
      render :registration, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @user.update(users_params)
      redirect_to users_path, notice: 'Пользователь изменен успешно.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    if @user.destroyed?
      redirect_to users_path, notice: 'Пользователь удален.'
    else
      redirect_to users_path, notice: @user.errors.full_messages.to_sentence.capitalize
    end
  end

  private

  def users_params
    params.require(:user).permit(:name, :login, :email, :password, :password_confirmation, :is_admin, :can_agree)
  end

  def require_registration
    redirect_to root_path if User.first
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
  <%= render 'layouts/form_errors', object: @user %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
  </div>
  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
  </div>
  <div>
    <%= f.label :login %><br />
    <%= f.text_field :login %><br />
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
  </div>
  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %><br />
  </div>
  <div>
    <%= f.check_box :is_admin %>
    <%= f.label :is_admin, "Администратор" %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div>
  <div>
    <%= user.name %>
  </div>
  <div>
    <%= user.email %>
  </div>
  <div>
    <%= user.login %>
  </div>
  <% if user.is_admin %>
    <div>
      Администратор
    </div>
  <% end %>
  <div>
    <%= link_to "Изменить", edit_user_path(user) %>
    <%= button_to "Удалить", user_path(user), method: :delete %>
  </div>
</div>
<hr>

app/views/users/edit.html.erb
<h1>Пользователь</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Пользователи</h1>
<%= link_to "Добавить", new_user_path %>
<br>
<br>
<%= render @users %>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>
<%= render "form", user: @user %>

app/views/users/registration.html.erb
<h1>Регистрация</h1>

<%= form_with model: @user, url: register_path do |f| %>
  <%= render 'layouts/form_errors', object: @user %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
  </div>
  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
  </div>
  <div>
    <%= f.label :login %><br />
    <%= f.text_field :login %><br />
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
  </div>
  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %><br />
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>