config/routes.rb
Rails.application.routes.draw do
  resources :sources, except: :show
  
  resources :users
  get '/registration', to: 'users#registration', as: 'registration'
  post '/register', to: 'users#register', as: 'register'
  resources :password_resets, only: %i[new create edit update]
  resource :user_session  
  
  resources :users_groups do
    resources :users_group_members, only: %i[create destroy]
    resources :organization_restrictions, only: %i[create destroy]
    resources :division_restrictions, only: %i[create destroy]
  end

  resources :expenses, only: %i[index show] do
    collection do
      get '/page/:page', action: :index
      get 'list'
    end
  end
  put '/expenses/:id/agree', to: 'expenses#agree', as: 'expense_agree'
  put '/expenses/:id/disagree', to: 'expenses#disagree', as: 'expense_disagree'

  resources :external_apps, except: :show

  get '/permission_error', to: 'pages#permission_error', as: 'permission_error'
  root "pages#home"

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'expenses', to: 'expenses#create'
        patch 'expense', to: 'expenses#update'
        put 'expense', to: 'expenses#update'
        delete 'expense', to: 'expenses#destroy'

        post 'organizations', to: 'organizations#create'
        patch 'organization', to: 'organizations#update'
        put 'organization', to: 'organizations#update'
        delete 'organization', to: 'organizations#destroy'

        post 'divisions', to: 'divisions#create'
        patch 'division', to: 'divisions#update'
        put 'division', to: 'divisions#update'
        delete 'division', to: 'divisions#destroy'
      end
    end
  end
end

app/models/external_app.rb
class ExternalApp < ApplicationRecord
  has_many :expenses

  validates :name, presence: true
  validates :token, uniqueness: { case_sensitive: true }

  before_validation :generate_token, on: :create

  encrypts :token, deterministic: true

  private

  def generate_token
    self.token = Digest::MD5.hexdigest(SecureRandom.hex)
  end
end

app/controllers/external_apps_controller.rb
class ExternalAppsController < ApplicationController
  before_action :require_login
  before_action :require_admin
  before_action :set_external_app, only: %i[edit update destroy]

  def index
    @external_apps = ExternalApp.all
  end

  def new
    @external_app = ExternalApp.new
  end

  def create
    @external_app = ExternalApp.new(external_app_params)

    if @external_app.save
      redirect_to external_apps_path, notice: 'Внешнее приложение добавлено успешно.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @external_app.update(external_app_params)
      redirect_to external_apps_path, notice: 'Внешнее приложение изменено успешно.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @external_app.destroy
    redirect_to external_apps_path, notice: 'Внешнее приложение удалено.'
  end

  private

  def external_app_params
    params.require(:external_app).permit(:name, :active, :callback_url)
  end

  def set_external_app
    @external_app = ExternalApp.find(params[:id])
  end
end

app/views/external_apps/_external_app.html.erb
<div>
  <div>
    <%= external_app.name %>
  </div>
  <div>
    <%= external_app.callback_url %>
  </div>
  <div>
    <% if external_app.active %>
      <%= "Активно" %>
    <% else %>
      <%= "Неактивно" %>
    <% end %>
  </div>
  <div>
    <%= link_to "Изменить", edit_external_app_path(external_app) %>
    <%= button_to "Удалить", external_app_path(external_app), method: :delete %>
  </div>
</div>
<hr>

app/views/external_apps/_form.html.erb
<%= form_with model: external_app do |form| %>
  <%= render 'layouts/form_errors', object: external_app %>

  <div>
    <%= form.label :name, "Наименование:" %>
    <%= form.text_field :name %>
  </div>

  <% if external_app.persisted? %>
    <div>
      <%= "Токен: #{external_app.token}" %>
    </div>
  <% end %>

  <div>
    <%= form.check_box :active %>
    <%= form.label :active, "Активный" %>
  </div>

  <div>
    <%= form.label :callback_url, "Callback URL:" %>
    <%= form.text_field :callback_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/external_apps/edit.html.erb
<h1>Внешнее приложение</h1>
<%= render "form", external_app: @external_app %>

app/views/external_apps/index.html.erb
<h1>Внешние приложения</h1>
<%= link_to "Добавить", new_external_app_path %>
<br>
<br>
<%= render @external_apps %>

app/views/external_apps/new.html.erb
<h1>Новов внешнее приложение</h1>
<%= render "form", external_app: @external_app %>