config/routes.rb
Rails.application.routes.draw do
  resources :sources, except: :show
  
  resources :users
  get '/registration', to: 'users#registration', as: 'registration'
  post '/register', to: 'users#register', as: 'register'
  resources :password_resets, only: %i[new create edit update]
  resource :user_session  
  
  resources :users_groups do
    resources :users_group_members, only: %i[create destroy]
    resources :organization_restrictions, only: %i[create destroy]
    resources :division_restrictions, only: %i[create destroy]
  end

  resources :expenses, only: %i[index show] do
    collection do
      get '/page/:page', action: :index
      get 'list'
    end
  end
  put '/expenses/:id/agree', to: 'expenses#agree', as: 'expense_agree'
  put '/expenses/:id/disagree', to: 'expenses#disagree', as: 'expense_disagree'

  resources :external_apps, except: :show

  get '/permission_error', to: 'pages#permission_error', as: 'permission_error'
  root "pages#home"

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'expenses', to: 'expenses#create'
        patch 'expense', to: 'expenses#update'
        put 'expense', to: 'expenses#update'
        delete 'expense', to: 'expenses#destroy'

        post 'organizations', to: 'organizations#create'
        patch 'organization', to: 'organizations#update'
        put 'organization', to: 'organizations#update'
        delete 'organization', to: 'organizations#destroy'

        post 'divisions', to: 'divisions#create'
        patch 'division', to: 'divisions#update'
        put 'division', to: 'divisions#update'
        delete 'division', to: 'divisions#destroy'
      end
    end
  end
end

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <%= object.errors.full_messages.to_sentence.capitalize %>
<% end %> 

app/views/layouts/_navigation.html.erb
<div>
  <%= link_to "Заявки", expenses_path %> |
  <% if current_user.is_admin %>
    <%= link_to "Банковские счета/кассы", sources_path %> |
    <%= link_to "Пользователи", users_path %>
    <%= link_to "Группы пользователей", users_groups_path %>
    <%= link_to "Внешние приложения", external_apps_path %>
  <% end %>
  <% if current_user %>
    <%= current_user.login %>
    <%= button_to "Выйти", user_session_path(current_user_session), method: :delete %>
  <% else %>
    <%= link_to "Войти", new_user_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CostsAgreeding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |flash_type, message| %>
      <%= message %>
    <% end %>

    <% if current_user %>
      <%= render 'layouts/navigation' %>
    <% end %>
  
    <%= yield %>
  </body>
</html>